version: 0.2

env:
  variables:
    BACKEND_REPO_NAME: "assimetria-backend"
    FRONTEND_REPO_NAME: "assimetria-frontend"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      # AWS_ACCOUNT_ID and AWS_REGION will be set as environment variables in CodeBuild
      - ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - REGION=${AWS_REGION}
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - echo "Using image tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building backend image..."
      - docker build -t $BACKEND_REPO_NAME:latest -f backend/Dockerfile backend
      - docker tag $BACKEND_REPO_NAME:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$BACKEND_REPO_NAME:$IMAGE_TAG

      - echo "Building frontend image..."
      - docker build -t $FRONTEND_REPO_NAME:latest -f frontend/Dockerfile frontend
      - docker tag $FRONTEND_REPO_NAME:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$FRONTEND_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing backend image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$BACKEND_REPO_NAME:$IMAGE_TAG

      - echo "Pushing frontend image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$FRONTEND_REPO_NAME:$IMAGE_TAG

      - echo "Build and push completed."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
