import dotenv from "dotenv";

dotenv.config();

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
const OPENROUTER_MODEL =
  process.env.OPENROUTER_MODEL ||
  "mistralai/mistral-7b-instruct:free";
const DEFAULT_ARTICLE_TOPIC =
  process.env.DEFAULT_ARTICLE_TOPIC || "technology and software";

/**
 * Calls the OpenRouter API (OpenAI-compatible chat completions)
 * to generate text from a prompt.
 */
async function generateRawTextFromAI(prompt) {
  if (!OPENROUTER_API_KEY) {
    throw new Error("OPENROUTER_API_KEY is not set");
  }

  const response = await fetch(
    "https://openrouter.ai/api/v1/chat/completions",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${OPENROUTER_API_KEY}`,
        "Content-Type": "application/json",
        // Optional but recommended headers:
        "HTTP-Referer": "https://github.com/helenomatoss/assimetria-auto-blog",
        "X-Title": "Assimetria Auto Blog"
      },
      body: JSON.stringify({
        model: OPENROUTER_MODEL,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        max_tokens: 500,
        temperature: 0.7
      })
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error("OpenRouter API error:", errorText);
    throw new Error(
      `OpenRouter API request failed with status ${response.status}`
    );
  }

  const data = await response.json();

  // OpenAI-style response shape
  const rawText =
    data.choices?.[0]?.message?.content || JSON.stringify(data);

  return rawText;
}

/**
 * Generates a blog article using the AI model.
 * Returns an object with { title, content, createdAt }.
 */
export async function generateArticle(topic = DEFAULT_ARTICLE_TOPIC) {
  const prompt = `
You are an assistant that writes concise technical blog posts.

Write a short blog article in English about: "${topic}".

The article should have:
- A clear title on the first line.
- Then a blank line.
- Then 3–6 short paragraphs of content.

Return only the article text without any additional explanations.
`;

  const raw = await generateRawTextFromAI(prompt);

  // Simple parsing: assume first line is the title, rest is content
  const lines = raw.split("\n").map((l) => l.trim());
  const nonEmptyLines = lines.filter((l) => l.length > 0);

  const title = nonEmptyLines[0] || "Untitled AI-generated article";
  const content =
    nonEmptyLines.slice(1).join("\n\n") ||
    "No content generated by the AI model.";

  const now = new Date().toISOString();

  return {
    title,
    content,
    createdAt: now
  };
}
