import dotenv from "dotenv";

dotenv.config();

const HUGGINGFACE_API_KEY = process.env.HUGGINGFACE_API_KEY;
const HUGGINGFACE_MODEL_ID =
  process.env.HUGGINGFACE_MODEL_ID || "gpt2";
const DEFAULT_ARTICLE_TOPIC =
  process.env.DEFAULT_ARTICLE_TOPIC || "technology and software";

/**
 * Calls the HuggingFace Inference API to generate raw text.
 */
async function generateRawTextFromAI(prompt) {
  if (!HUGGINGFACE_API_KEY) {
    throw new Error("HUGGINGFACE_API_KEY is not set");
  }

  const response = await fetch(
    `https://api-inference.huggingface.co/models/${HUGGINGFACE_MODEL_ID}`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${HUGGINGFACE_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        inputs: prompt,
        parameters: {
          max_new_tokens: 300,
          temperature: 0.7,
          do_sample: true
        }
      })
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error("HuggingFace API error:", errorText);
    throw new Error(
      `HuggingFace API request failed with status ${response.status}`
    );
  }

  const data = await response.json();

  // Different models can have slightly different response shapes,
  // but most text-generation models return an array with "generated_text".
  const rawText =
    Array.isArray(data) && data[0]?.generated_text
      ? data[0].generated_text
      : JSON.stringify(data);

  return rawText;
}

/**
 * Generates a blog article using the AI model.
 * Returns an object with { title, content, createdAt }.
 */
export async function generateArticle(topic = DEFAULT_ARTICLE_TOPIC) {
  const prompt = `
You are an assistant that writes concise technical blog posts.

Write a short blog article in English about: "${topic}".

The article should have:
- A clear title on the first line.
- Then a blank line.
- Then 3–6 short paragraphs of content.

Return only the article text without any additional explanations.
`;

  const raw = await generateRawTextFromAI(prompt);

  // Simple parsing: assume first line is the title, rest is content
  const lines = raw.split("\n").map((l) => l.trim());
  const nonEmptyLines = lines.filter((l) => l.length > 0);

  const title = nonEmptyLines[0] || "Untitled AI-generated article";
  const content =
    nonEmptyLines.slice(1).join("\n\n") ||
    "No content generated by the AI model.";

  const now = new Date().toISOString();

  return {
    title,
    content,
    createdAt: now
  };
}
