// frontend/src/pages/ArticlesListPage.tsx
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import type { Article } from "../api/client";
import { fetchArticles } from "../api/client";

function formatDate(dateString: string) {
  const date = new Date(dateString);
  return date.toLocaleDateString("pt-BR", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
}

const ArticlesListPage: React.FC = () => {
  const [articles, setArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let isMounted = true;

    const loadArticles = async () => {
      try {
        const data = await fetchArticles();
        if (isMounted) {
          setArticles(data);
          setError(null);
        }
      } catch (err: any) {
        if (isMounted) {
          console.error(err);
          setError("Failed to load articles. Please try again.");
        }
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    };

    loadArticles();

    return () => {
      isMounted = false;
    };
  }, []);

  return (
    <main className="page">
      <header className="page-header">
        <div className="page-header-left">
          <h1 className="page-title">AI-generated technical articles</h1>
          <p className="page-subtitle">
            Fresh content automatically generated by your backend, ready to be read.
          </p>
        </div>
        <div className="page-header-right">
          <span className="pill pill-latest">Latest</span>
        </div>
      </header>

      {loading && (
        <section className="page-section">
          <div className="page-status">Loading articles…</div>
        </section>
      )}

      {error && (
        <section className="page-section">
          <div className="page-status page-status-error">{error}</div>
        </section>
      )}

      {!loading && !error && (
        <section className="page-section">
          <div className="articles-list">
            {articles.map((article) => (
              <article key={article.id} className="article-card">
                <div className="article-card-main">
                  <h2 className="article-title">{article.title}</h2>
                  <p className="article-meta">
                    <span>{formatDate(article.createdAt)}</span>
                    <span className="dot">•</span>
                    <span>~3–5 min read</span>
                  </p>
                  <p className="article-excerpt">
                    {article.content.length > 280
                      ? `${article.content.slice(0, 280)}…`
                      : article.content}
                  </p>
                </div>
                <div className="article-card-footer">
                  <Link
                    to={`/articles/${article.id}`}
                    className="article-link"
                  >
                    Read article ↗
                  </Link>
                </div>
              </article>
            ))}
          </div>
        </section>
      )}
    </main>
  );
};

export default ArticlesListPage;
