import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { type Article, fetchArticles } from "../api/client";

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-GB"); // 04/12/2025
}

export default function ArticlesListPage() {
  const [articles, setArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      try {
        setLoading(true);
        const data = await fetchArticles();
        setArticles(data);
      } catch (err) {
        console.error(err);
        setError("Failed to load articles.");
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  if (loading) {
    return (
      <main className="max-w-5xl mx-auto py-16 text-slate-300">
        Loading articles...
      </main>
    );
  }

  if (error) {
    return (
      <main className="max-w-5xl mx-auto py-16 text-red-400">{error}</main>
    );
  }

  return (
    <main className="max-w-5xl mx-auto py-12 space-y-8">
      <section className="space-y-2">
        <p className="text-xs uppercase tracking-[0.3em] text-sky-400">
          Latest
        </p>
        <h1 className="text-3xl md:text-4xl font-semibold text-slate-50">
          AI-generated technical articles
        </h1>
        <p className="text-sm text-slate-400">
          Fresh content automatically generated by your backend, ready to be
          read.
        </p>
      </section>

      <section className="space-y-4">
        {articles.map((article) => (
          <article
            key={article.id}
            className="rounded-2xl bg-slate-900/60 border border-slate-700/60 px-6 py-5 md:px-8 md:py-6 flex flex-col gap-3"
          >
            <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-2">
              <div className="space-y-1">
                <h2 className="text-lg md:text-xl font-medium text-slate-100">
                  {article.title}
                </h2>
                <p className="text-xs text-slate-400">
                  {formatDate(article.createdAt)} • ~3–5 min read
                </p>
              </div>

              <Link
                to={`/articles/${article.id}`}
                className="inline-flex items-center justify-center rounded-full border border-sky-400/60 px-4 py-1.5 text-xs font-medium text-sky-200 hover:bg-sky-500/10 transition-colors"
              >
                Read article ↗
              </Link>
            </div>

            <p className="text-sm text-slate-300 whitespace-pre-line">
              {article.content.slice(0, 220)}…
            </p>
          </article>
        ))}
      </section>
    </main>
  );
}

