import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { type Article, fetchArticles } from "../api/client";

function formatDate(iso: string) {
  const d = new Date(iso);
  return d.toLocaleDateString("pt-BR", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
}

function ArticlesListPage() {
  const [articles, setArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      try {
        const data = await fetchArticles();
        setArticles(data);
      } catch (err) {
        console.error(err);
        setError("Failed to load articles.");
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  return (
    <>
      <header className="page-header">
        <div className="page-kicker">Latest</div>
        <h1 className="page-title">AI-generated technical articles</h1>
        <p className="page-description">
          Fresh content automatically generated by your backend, ready to be read.
        </p>
      </header>

      {loading && <p className="state-message">Loading articles…</p>}
      {error && <p className="state-message error">{error}</p>}

      {!loading && !error && (
        <section className="article-list">
          {articles.map((article) => (
            <article key={article.id} className="article-card">
              <h2 className="article-card-title">
                <Link to={`/articles/${article.id}`}>{article.title}</Link>
              </h2>

              <div className="article-meta">
                <span>{formatDate(article.createdAt)}</span>
                <span className="article-meta-dot" />
                <span>~3–5 min read</span>
              </div>

              <p className="article-excerpt">
                {article.content.slice(0, 220)}
                {article.content.length > 220 ? "…" : ""}
              </p>

              <div className="article-card-cta">
                <Link to={`/articles/${article.id}`} className="article-link-chip">
                  <span>Read article</span> ↗
                </Link>
              </div>
            </article>
          ))}
        </section>
      )}
    </>
  );
}

export default ArticlesListPage;
